import Link from "next/link";
import { backendFetchJson } from "@/lib/backend.server";
import { AppFormModal } from "@/components/AppFormModal";
import { Card, Table } from "@/components/ui";
import { PettyCashReturnCreateForm } from "./PettyCashReturnCreateForm";
import { money, returnStatusLabel, type ReturnDto } from "./types";
type Fund = { id: string; code: string; name: string; balance: number; isActive: boolean };
type Permissions = { permissions: string[] };
export default async function Page() { const [rows, funds, access] = await Promise.all([backendFetchJson<ReturnDto[]>("/finance/petty-cash-returns"), backendFetchJson<Fund[]>("/finance/petty-cash-funds"), backendFetchJson<Permissions>("/me/permissions")]); const canCreate = access.permissions.includes("Finance.PettyCashReturn.Create"); return <div className="space-y-6"><div className="flex flex-wrap items-start justify-between gap-3"><div><h1 className="text-2xl font-semibold">Return Petty Cash to Head Office</h1><p className="mt-1 text-sm text-zinc-500">Return reconciled cash from the physical fund. This does not alter expense categories or job costs.</p></div>{canCreate ? <AppFormModal title="Prepare Fund Return" description="Record the physical cash being returned." buttonLabel="+ Prepare Return"><PettyCashReturnCreateForm funds={funds.filter((fund) => fund.isActive)} /></AppFormModal> : null}</div><Card><div className="overflow-auto"><Table><thead><tr className="border-b text-left text-xs uppercase text-zinc-500"><th className="py-2 pr-3">Return</th><th className="py-2 pr-3">Fund</th><th className="py-2 pr-3">Prepared by</th><th className="py-2 pr-3">Status</th><th className="py-2 pr-3 text-right">Amount</th><th className="py-2 pr-3">Receipt</th></tr></thead><tbody>{rows.map((row) => <tr key={row.id} className="border-b"><td className="py-2 pr-3"><Link className="font-mono text-xs underline" href={`/finance/petty-cash-returns/${row.id}`}>{row.number}</Link>{row.isLegacyCategoryReturn ? <div className="text-xs text-amber-600">Legacy category return</div> : null}</td><td className="py-2 pr-3">{row.pettyCashFundCode ?? "-"}</td><td className="py-2 pr-3">{row.preparedByName}</td><td className="py-2 pr-3">{returnStatusLabel[row.status] ?? row.status}</td><td className="py-2 pr-3 text-right">{money(row.totalAmount)}</td><td className="py-2 pr-3">{row.receiptReference ?? "-"}</td></tr>)}{rows.length === 0 ? <tr><td colSpan={6} className="py-8 text-center text-sm text-zinc-500">No fund returns.</td></tr> : null}</tbody></Table></div></Card></div>; }
